name: Run Pytest

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  test:
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        include:
          - os: ubuntu-latest
            python-version: '3.6.15'
          - os: ubuntu-latest
            python-version: '3.10.15'
          - os: ubuntu-latest
            python-version: '3.12.6'
          # - os: macos-latest
          #   python-version: '3.12.6'
          - os: windows-latest
            python-version: '3.12.6'

    steps:
    - name: Check out repository
      uses: actions/checkout@v3

    - name: Set up Python
      uses: actions/setup-python@v4
      with:
        python-version: ${{ matrix.python-version }}

    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install .

    - name: Run tests
      run: |
        pytest
